# Generated by Django 4.1.5 on 2023-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=12)),
                ('House_No', models.CharField(blank=True, max_length=30, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Message', models.TextField()),
            ],
        ),
    ]
