# Generated by Django 4.1.5 on 2023-01-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Home_number', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('Contact_no', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
                ('Interested_at', models.CharField(max_length=50)),
                ('Available_at', models.CharField(max_length=50)),
                ('Interested_for', models.CharField(max_length=50)),
                ('experience', models.TextField()),
            ],
        ),
    ]
