# Generated by Django 4.1.5 on 2023-01-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='l_name',
            new_name='lname',
        ),
    ]
