# Generated by Django 4.1.5 on 2023-01-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_f_name_volunteer_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='fname',
            new_name='namef',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='lname',
            new_name='namel',
        ),
    ]
