# Generated by Django 4.1.5 on 2023-01-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_volunteer_namef_remove_volunteer_namel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='gender',
        ),
    ]
