# Generated by Django 4.1.5 on 2023-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_check_delete_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='value1',
            new_name='volunteer_fname',
        ),
        migrations.RemoveField(
            model_name='check',
            name='value2',
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_gender',
            field=models.CharField(default='male', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_lname',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
