# Generated by Django 4.1.5 on 2023-01-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rename_value1_check_volunteer_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='volunteer_age',
            field=models.CharField(default='18', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_city',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_home_number',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_pincode',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_state',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
