# Generated by Django 4.1.5 on 2023-01-10 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_check_volunteer_age_check_volunteer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='volunteer_available_at',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_date',
            field=models.DateField(default=datetime.date(2023, 1, 11)),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_experience',
            field=models.TextField(default='Pata Nahi'),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_interested_at',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_interested_for',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='check',
            name='volunteer_phone',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
