# Generated by Django 4.1.5 on 2023-01-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_check_volunteer_available_at_check_volunteer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='volunteer_available_at',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_interested_at',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_interested_for',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
