# Generated by Django 4.1.5 on 2023-01-10 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_check_volunteer_available_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='volunteer_age',
            field=models.CharField(default='18', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_city',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_date',
            field=models.DateField(default=datetime.date(2023, 1, 11), null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_email',
            field=models.EmailField(default='none@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_experience',
            field=models.TextField(default='Pata Nahi', null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_gender',
            field=models.CharField(default='male', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_home_number',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_lname',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_phone',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_pincode',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='volunteer_state',
            field=models.CharField(default='none', max_length=50, null=True),
        ),
    ]
